Repository IT-Cotato/10th-Economic-Learning-BE, pull requests merged in 2024-12, with the labels that each got.

#13 Feat : 소셜 로그인 구현 #12
  build.gradle
  src/main/java/com/ripple/BE/auth/client/KakaoApiClient.java
  src/main/java/com/ripple/BE/auth/controller/AuthController.java
  src/main/java/com/ripple/BE/auth/dto/LoginRequest.java
  src/main/java/com/ripple/BE/auth/dto/SignupRequest.java
  src/main/java/com/ripple/BE/auth/dto/kakao/KakaoAccount.java
  src/main/java/com/ripple/BE/auth/dto/kakao/KakaoProfile.java
  src/main/java/com/ripple/BE/auth/dto/kakao/KakaoProperties.java
  src/main/java/com/ripple/BE/auth/dto/kakao/KakaoTokenResponse.java
  src/main/java/com/ripple/BE/auth/dto/kakao/KakaoUserInfoResponse.java
  src/main/java/com/ripple/BE/auth/filter/JwtAuthFilter.java
  src/main/java/com/ripple/BE/auth/jwt/JwtTokenProvider.java
  src/main/java/com/ripple/BE/auth/service/AuthService.java
  src/main/java/com/ripple/BE/chatbot/domain/ChatSession.java
  src/main/java/com/ripple/BE/dailyQuest/domain/DailyQuest.java
  src/main/java/com/ripple/BE/global/config/JpaConfig.java
  src/main/java/com/ripple/BE/global/config/SwaggerConfig.java
  src/main/java/com/ripple/BE/global/config/WebClientConfig.java
  src/main/java/com/ripple/BE/global/config/WebConfig.java
  src/main/java/com/ripple/BE/global/config/WebSecurityConfig.java
  src/main/java/com/ripple/BE/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/ripple/BE/learning/domain/Concept.java
  src/main/java/com/ripple/BE/learning/domain/Quiz.java
  src/main/java/com/ripple/BE/learning/domain/QuizScrap.java
  src/main/java/com/ripple/BE/news/domain/NewsScrap.java
  src/main/java/com/ripple/BE/post/domain/Comment.java
  src/main/java/com/ripple/BE/post/domain/Post.java
  src/main/java/com/ripple/BE/post/domain/PostLike.java
  src/main/java/com/ripple/BE/post/domain/PostScrap.java
  src/main/java/com/ripple/BE/term/domain/TermScrap.java
  src/main/java/com/ripple/BE/user/controller/UserController.java
  src/main/java/com/ripple/BE/user/domain/Attendance.java
  src/main/java/com/ripple/BE/user/domain/CustomUserDetails.java
  src/main/java/com/ripple/BE/user/domain/User.java
  src/main/java/com/ripple/BE/user/domain/UserProgress.java
  src/main/java/com/ripple/BE/user/domain/type/AgeRange.java
  src/main/java/com/ripple/BE/user/domain/type/BusinessType.java
  src/main/java/com/ripple/BE/user/domain/type/Gender.java
  src/main/java/com/ripple/BE/user/domain/type/Job.java
  src/main/java/com/ripple/BE/user/domain/type/LearningType.java
  src/main/java/com/ripple/BE/user/domain/type/Level.java
  src/main/java/com/ripple/BE/user/domain/type/LoginType.java
  src/main/java/com/ripple/BE/user/domain/type/Role.java
  src/main/java/com/ripple/BE/user/dto/UpdateUserProfileRequest.java
  src/main/java/com/ripple/BE/user/exception/UserException.java
  src/main/java/com/ripple/BE/user/exception/errorcode/UserErrorCode.java
  src/main/java/com/ripple/BE/user/repository/UserRepository.java
  src/main/java/com/ripple/BE/user/service/CustomUserDetailService.java
  src/main/java/com/ripple/BE/user/service/UserService.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: :bug: Bug, Chore, :sparkles: Feat

#16 Feat : 유저 정보 입력 필드 수정 (#12)
  src/main/java/com/ripple/BE/user/domain/User.java
  src/main/java/com/ripple/BE/user/dto/UpdateUserProfileRequest.java
Labels: :sparkles: Feat

#18 Feat : 개념 학습 API 구현
  build.gradle
  src/main/java/com/ripple/BE/global/excel/ExcelUtils.java
  src/main/java/com/ripple/BE/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/ripple/BE/learning/controller/ConceptController.java
  src/main/java/com/ripple/BE/learning/controller/LearningController.java
  src/main/java/com/ripple/BE/learning/domain/Concept.java
  src/main/java/com/ripple/BE/learning/domain/LearningSet.java
  src/main/java/com/ripple/BE/learning/domain/LearningSetComplete.java
  src/main/java/com/ripple/BE/learning/domain/Quiz.java
  src/main/java/com/ripple/BE/learning/dto/ConceptDTO.java
  src/main/java/com/ripple/BE/learning/dto/ConceptListDTO.java
  src/main/java/com/ripple/BE/learning/dto/LearningSetCompleteDTO.java
  src/main/java/com/ripple/BE/learning/dto/LearningSetCompleteListDTO.java
  src/main/java/com/ripple/BE/learning/dto/LearningSetDTO.java
  src/main/java/com/ripple/BE/learning/dto/LearningSetListDTO.java
  src/main/java/com/ripple/BE/learning/dto/ProgressDTO.java
  src/main/java/com/ripple/BE/learning/dto/QuizDTO.java
  src/main/java/com/ripple/BE/learning/dto/request/LearningSetRequest.java
  src/main/java/com/ripple/BE/learning/dto/response/ConceptListResponse.java
  src/main/java/com/ripple/BE/learning/dto/response/ConceptResponse.java
  src/main/java/com/ripple/BE/learning/dto/response/LearningSetPreviewListResponse.java
  src/main/java/com/ripple/BE/learning/dto/response/LearningSetPreviewResponse.java
  src/main/java/com/ripple/BE/learning/dto/response/LearningSetProgressResponse.java
  src/main/java/com/ripple/BE/learning/event/LearningSetCompleteEventListener.java
  src/main/java/com/ripple/BE/learning/exception/LearningException.java
  src/main/java/com/ripple/BE/learning/exception/errorcode/LearningErrorCode.java
  src/main/java/com/ripple/BE/learning/repository/LearningSetCompleteRepository.java
  src/main/java/com/ripple/BE/learning/repository/LearningSetRepository.java
  src/main/java/com/ripple/BE/learning/service/ConceptService.java
  src/main/java/com/ripple/BE/learning/service/LearningAdminService.java
  src/main/java/com/ripple/BE/learning/service/LearningSetService.java
  src/main/java/com/ripple/BE/user/domain/User.java
  src/main/java/com/ripple/BE/user/repository/UserRepository.java
  src/main/resources/application-local.yml
  src/main/resources/static/excel/example.xlsx
Labels: :recycle: Refactor, :sparkles: Feat

#17 Feat : 레벨테스트 구현 (#14)
  src/main/java/com/ripple/BE/global/config/WebSecurityConfig.java
  src/main/java/com/ripple/BE/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/ripple/BE/learning/controller/LevelTestController.java
  src/main/java/com/ripple/BE/learning/dto/AnswerDTO.java
  src/main/java/com/ripple/BE/learning/dto/QuizDTO.java
  src/main/java/com/ripple/BE/learning/dto/QuizListDTO.java
  src/main/java/com/ripple/BE/learning/dto/QuizSubmitDTO.java
  src/main/java/com/ripple/BE/learning/dto/request/AddLevelTestQuizRequest.java
  src/main/java/com/ripple/BE/learning/dto/request/SubmitLevelTestRequest.java
  src/main/java/com/ripple/BE/learning/dto/response/LevelTestQuizListResponse.java
  src/main/java/com/ripple/BE/learning/dto/response/LevelTestResultResponse.java
  src/main/java/com/ripple/BE/learning/dto/response/QuizResponse.java
  src/main/java/com/ripple/BE/learning/exception/QuizException.java
  src/main/java/com/ripple/BE/learning/exception/errorcode/QuizErrorCode.java
  src/main/java/com/ripple/BE/learning/repository/QuizRepository.java
  src/main/java/com/ripple/BE/learning/service/LevelTestService.java
  src/main/java/com/ripple/BE/user/controller/UserController.java
  src/main/java/com/ripple/BE/user/domain/User.java
Labels: :sparkles: Feat
