Repository IT-Cotato/10th-Economic-Learning-BE, pull requests merged in 2025-02, with the labels that each got.

#47 [Feat] 인기 게시글 목록 조회 기능 구현
  src/main/java/com/ripple/BE/post/controller/PostController.java
  src/main/java/com/ripple/BE/post/dto/response/PopularPostPreviewListResponse.java
  src/main/java/com/ripple/BE/post/dto/response/PopularPostPreviewResponse.java
  src/main/java/com/ripple/BE/post/repository/post/PostRepositoryCustom.java
  src/main/java/com/ripple/BE/post/repository/post/PostRepositoryCustomImpl.java
  src/main/java/com/ripple/BE/post/service/PostService.java
Labels: :sparkles: Feat

#48 [Feat] 푸시 알람 변경 기능, 레벨업, 목록 조회 api Getmapping으로 수정
  src/main/java/com/ripple/BE/learning/controller/LearningController.java
  src/main/java/com/ripple/BE/learning/service/concept/ConceptService.java
  src/main/java/com/ripple/BE/learning/service/quiz/QuizService.java
  src/main/java/com/ripple/BE/user/controller/UserController.java
  src/main/java/com/ripple/BE/user/domain/User.java
  src/main/java/com/ripple/BE/user/service/UserProgressService.java
  src/main/java/com/ripple/BE/user/service/UserService.java
Labels: :bug: Bug, :recycle: Refactor, :sparkles: Feat

#50 [Feat] 스크랩 기능 추가 및 레벨별 진도율 조회 메소드 기능 수정
  src/main/java/com/ripple/BE/learning/controller/ConceptController.java
  src/main/java/com/ripple/BE/learning/controller/LearningController.java
  src/main/java/com/ripple/BE/learning/controller/QuizController.java
  src/main/java/com/ripple/BE/learning/exception/errorcode/LearningErrorCode.java
  src/main/java/com/ripple/BE/learning/exception/errorcode/QuizErrorCode.java
  src/main/java/com/ripple/BE/learning/repository/conceptScrap/ConceptScrapRepository.java
  src/main/java/com/ripple/BE/learning/repository/quizScrap/QuizScrapRepository.java
  src/main/java/com/ripple/BE/learning/service/concept/ConceptService.java
  src/main/java/com/ripple/BE/learning/service/quiz/QuizService.java
  src/main/java/com/ripple/BE/news/controller/NewsController.java
  src/main/java/com/ripple/BE/news/dto/NewsListDTO.java
  src/main/java/com/ripple/BE/news/repository/newscrap/NewsScrapRepository.java
  src/main/java/com/ripple/BE/news/repository/newscrap/NewsScrapRepositoryCustom.java
  src/main/java/com/ripple/BE/news/repository/newscrap/NewsScrapRepositoryCustomImpl.java
  src/main/java/com/ripple/BE/post/controller/PostController.java
  src/main/java/com/ripple/BE/post/repository/postscrap/PostScrapRepositoryCustomImpl.java
  src/main/java/com/ripple/BE/term/dto/TermListDTO.java
  src/main/java/com/ripple/BE/term/repository/TermScrapRepository.java
  src/main/java/com/ripple/BE/term/repository/TermScrapRepositoryCustom.java
  src/main/java/com/ripple/BE/term/repository/TermScrapRepositoryCustomImpl.java
  src/main/java/com/ripple/BE/user/controller/UserController.java
  src/main/java/com/ripple/BE/user/dto/ProgressResponse.java
  src/main/java/com/ripple/BE/user/service/MyPageService.java
  src/main/java/com/ripple/BE/user/service/UserProgressService.java
Labels: :recycle: Refactor, :sparkles: Feat

#54 [Bug] 답글 삭제 오류 수정
  src/main/java/com/ripple/BE/post/repository/comment/CommentRepositoryCustomImpl.java
  src/main/java/com/ripple/BE/post/service/PostService.java
Labels: :bug: Bug

#58 Feat : 챗봇 기능을 수정합니다 (#24)
  src/main/java/com/ripple/BE/chatbot/controller/ChatbotController.java
  src/main/java/com/ripple/BE/chatbot/domain/ChatMessage.java
  src/main/java/com/ripple/BE/chatbot/repository/ChatbotRepository.java
  src/main/java/com/ripple/BE/chatbot/service/ChatbotService.java
Labels: :sparkles: Feat

#57 Feat : 개념학습 스웨거 설명 추가 (#15)
  src/main/java/com/ripple/BE/learning/controller/ConceptController.java
Labels: :memo: Docs

#60 [Feat] 경제 톡톡 저장 기능 구현 및 기타 버그 수정
  build.gradle
  src/main/java/com/ripple/BE/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/ripple/BE/notification/service/NotificationService.java
  src/main/java/com/ripple/BE/post/controller/ToktokController.java
  src/main/java/com/ripple/BE/post/domain/Post.java
  src/main/java/com/ripple/BE/post/dto/ToktokDTO.java
  src/main/java/com/ripple/BE/post/dto/ToktokListDTO.java
  src/main/java/com/ripple/BE/post/dto/response/CommentResponse.java
  src/main/java/com/ripple/BE/post/dto/response/PostResponse.java
  src/main/java/com/ripple/BE/post/dto/response/ToktokPreviewListResponse.java
  src/main/java/com/ripple/BE/post/dto/response/ToktokPreviewResponse.java
  src/main/java/com/ripple/BE/post/dto/response/ToktokResponse.java
  src/main/java/com/ripple/BE/post/exception/errorcode/PostErrorCode.java
  src/main/java/com/ripple/BE/post/repository/post/PostRepository.java
  src/main/java/com/ripple/BE/post/repository/post/PostRepositoryCustomImpl.java
  src/main/java/com/ripple/BE/post/service/ToktokAdminService.java
  src/main/java/com/ripple/BE/post/service/ToktokService.java
  src/main/java/com/ripple/BE/search/controller/SearchController.java
  src/main/java/com/ripple/BE/search/service/SearchService.java
  src/main/resources/static/excel/toktok.xlsx
Labels: :bug: Bug, :sparkles: Feat

#62 [Refactor] API Swagger 설명 추가
  src/main/java/com/ripple/BE/learning/controller/QuizController.java
  src/main/java/com/ripple/BE/news/controller/NewsController.java
  src/main/java/com/ripple/BE/post/controller/PostController.java
  src/main/java/com/ripple/BE/post/controller/ToktokController.java
  src/main/java/com/ripple/BE/search/controller/SearchController.java
Labels: :recycle: Refactor

#64 [Refactor] 경제 톡톡 엑셀 파일 구조 수정 및 이미지 추출 로직 수정
  src/main/java/com/ripple/BE/image/controller/ImageController.java
  src/main/java/com/ripple/BE/image/dto/response/ImageUrlResponse.java
  src/main/java/com/ripple/BE/image/repository/ImageRepository.java
  src/main/java/com/ripple/BE/image/s3/S3Uploader.java
  src/main/java/com/ripple/BE/image/service/ImageService.java
  src/main/java/com/ripple/BE/post/service/ToktokAdminService.java
  src/main/resources/static/excel/toktok.xlsx
Labels: :memo: Docs, :recycle: Refactor

#65 Refact : 레벨테스트 제출 수정 (#14)
  src/main/java/com/ripple/BE/learning/dto/response/LevelTestAnswerDTO.java
  src/main/java/com/ripple/BE/learning/dto/response/LevelTestResultResponse.java
  src/main/java/com/ripple/BE/learning/service/LevelTestService.java
Labels: :recycle: Refactor

#66 Feat : 유저 프로필 수정 api 추가 (#25)
  src/main/java/com/ripple/BE/user/controller/UserController.java
  src/main/java/com/ripple/BE/user/domain/User.java
  src/main/java/com/ripple/BE/user/dto/request/PatchUserProfileRequest.java
  src/main/java/com/ripple/BE/user/exception/errorcode/UserErrorCode.java
  src/main/java/com/ripple/BE/user/repository/UserRepository.java
  src/main/java/com/ripple/BE/user/service/UserService.java
Labels: :sparkles: Feat

#67 [Feat] 퀘스트, 사용자 관련 오류 (#25)
  src/main/java/com/ripple/BE/learning/service/LevelTestService.java
  src/main/java/com/ripple/BE/learning/service/concept/ConceptService.java
  src/main/java/com/ripple/BE/learning/service/quiz/QuizService.java
  src/main/java/com/ripple/BE/user/controller/UserController.java
  src/main/java/com/ripple/BE/user/domain/User.java
  src/main/java/com/ripple/BE/user/dto/UserCompletedDTO.java
  src/main/java/com/ripple/BE/user/dto/UserInfoDTO.java
  src/main/java/com/ripple/BE/user/dto/response/UserCompletedResponse.java
  src/main/java/com/ripple/BE/user/dto/response/UserInfoResponse.java
  src/main/java/com/ripple/BE/user/service/MyPageService.java
  src/main/java/com/ripple/BE/user/service/UserService.java
Labels: :recycle: Refactor, :sparkles: Feat

#68 [Debug / Feat] post 관련 오류 수정 및 기능 추가 (#68)
  src/main/java/com/ripple/BE/post/dto/ToktokDTO.java
  src/main/java/com/ripple/BE/post/dto/response/CommentResponse.java
  src/main/java/com/ripple/BE/post/dto/response/PostResponse.java
  src/main/java/com/ripple/BE/post/dto/response/ToktokPreviewResponse.java
  src/main/java/com/ripple/BE/post/dto/response/ToktokResponse.java
  src/main/java/com/ripple/BE/post/repository/comment/CommentRepositoryCustom.java
  src/main/java/com/ripple/BE/post/repository/comment/CommentRepositoryCustomImpl.java
  src/main/java/com/ripple/BE/post/service/ToktokService.java
  src/main/java/com/ripple/BE/user/dto/CommunityUserDTO.java
  src/main/java/com/ripple/BE/user/dto/UserRandomProfileDTO.java
  src/main/java/com/ripple/BE/user/dto/UserRandomProfileListDTO.java
  src/main/java/com/ripple/BE/user/dto/response/UserRandomProfileListResponse.java
  src/main/java/com/ripple/BE/user/dto/response/UserRandomProfileResponse.java
Labels: :bug: Bug, :sparkles: Feat

#69 [Refact] 유저가 댓글단 글 응답 형식 변경 (#25)
  src/main/java/com/ripple/BE/post/repository/comment/CommentRepository.java
  src/main/java/com/ripple/BE/post/repository/post/PostRepository.java
  src/main/java/com/ripple/BE/user/controller/UserController.java
  src/main/java/com/ripple/BE/user/dto/UserCommentDTO.java
  src/main/java/com/ripple/BE/user/dto/UserCommentListDTO.java
  src/main/java/com/ripple/BE/user/dto/response/UserCommentListResponse.java
  src/main/java/com/ripple/BE/user/dto/response/UserCommentResponse.java
  src/main/java/com/ripple/BE/user/service/MyPageService.java
Labels: :recycle: Refactor

#76 [Bug] SSE 커넥션 풀 부족 문제 수정
  src/main/java/com/ripple/BE/image/domain/Image.java
  src/main/java/com/ripple/BE/learning/exception/errorcode/QuizErrorCode.java
  src/main/java/com/ripple/BE/learning/service/quiz/QuizService.java
  src/main/java/com/ripple/BE/notification/service/NotificationService.java
  src/main/java/com/ripple/BE/notification/service/SseEmitterManager.java
Labels: :bug: Bug

#77 [Refact] : 게시물 상세 조회 시 작성자 id 추가
  src/main/java/com/ripple/BE/post/dto/response/PostResponse.java
Labels: :recycle: Refactor

#78 Bug : 사용자 조회 null pointer 오류 수정 및 기타 수정
  src/main/java/com/ripple/BE/news/service/NewsService.java
  src/main/java/com/ripple/BE/post/dto/response/ToktokPreviewResponse.java
  src/main/java/com/ripple/BE/user/service/UserService.java
Labels: :bug: Bug

#79 Refact : 경제 톡톡 게시물 상세 조회 스크랩 수 추가
  src/main/java/com/ripple/BE/post/dto/response/ToktokResponse.java
Labels: :recycle: Refactor
