Repository IT-Cotato/10th-Economic-Learning-BE, pull requests merged in 2025-06, with the labels that each got.

#104 [Feat] 엑셀 기반 초기 데이터 자동 생성 및 Toktok 저장 로직 개선 (#103)
  src/main/java/com/ripple/BE/global/init/StartupInitializer.java
  src/main/java/com/ripple/BE/learning/application/learningset/LearningAdminService.java
  src/main/java/com/ripple/BE/post/application/impl/post/PostQueryService.java
  src/main/java/com/ripple/BE/post/application/impl/toktok/ToktokAdminService.java
  src/main/java/com/ripple/BE/post/exception/errorcode/PostErrorCode.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/post/ToktokQueryRepositoryImpl.java
  src/main/resources/static/excel/learningset.xlsx
  src/main/resources/static/excel/toktok.xlsx
Labels: :recycle: Refactor, :sparkles: Feat

#109 [Feat] 에러 로그 파일 분리 저장 및 Discord 알림 기능 추가
  build.gradle
  docker-compose.yml
  src/main/java/com/ripple/BE/auth/controller/AuthController.java
  src/main/resources/application-prod.yml
  src/main/resources/logback-spring.xml
Labels: :sparkles: Feat

#110 [Chore] 운영-로그-테스트-API-제거
  src/main/java/com/ripple/BE/auth/controller/AuthController.java
Labels: Chore

#114 [Feat] 학습 세트 별 완료한 퀴즈 조회 (#113)
  src/main/java/com/ripple/BE/learning/application/quiz/QuizService.java
  src/main/java/com/ripple/BE/learning/controller/QuizController.java
  src/main/java/com/ripple/BE/learning/dto/response/quiz/QuizCompletionDTO.java
  src/main/java/com/ripple/BE/learning/persistence/UserLearningSetRepository.java
  src/main/java/com/ripple/BE/learning/persistence/impl/UserLearningSetRepositoryImpl.java
  src/main/java/com/ripple/BE/learning/persistence/jpa/repository/learningset/UserLearningSetJpaRepository.java
Labels: :sparkles: Feat

#116 [Feat] 회원 탈퇴 구현 (#107)
  src/main/java/com/ripple/BE/auth/controller/AuthController.java
  src/main/java/com/ripple/BE/auth/controller/AuthControllerV2.java
  src/main/java/com/ripple/BE/image/persistence/ImageRepository.java
  src/main/java/com/ripple/BE/image/persistence/impl/ImageRepositoryImpl.java
  src/main/java/com/ripple/BE/image/persistence/jpa/repository/ImageJpaRepository.java
  src/main/java/com/ripple/BE/learning/persistence/ConceptScrapRepository.java
  src/main/java/com/ripple/BE/learning/persistence/FailQuizRepository.java
  src/main/java/com/ripple/BE/learning/persistence/QuizScrapRepository.java
  src/main/java/com/ripple/BE/learning/persistence/UserLearningSetRepository.java
  src/main/java/com/ripple/BE/learning/persistence/impl/ConceptScrapRepositoryImpl.java
  src/main/java/com/ripple/BE/learning/persistence/impl/FailQuizRepositoryImpl.java
  src/main/java/com/ripple/BE/learning/persistence/impl/QuizScrapRepositoryImpl.java
  src/main/java/com/ripple/BE/learning/persistence/impl/UserLearningSetRepositoryImpl.java
  src/main/java/com/ripple/BE/learning/persistence/jpa/repository/conceptscrap/ConceptScrapJpaRepository.java
  src/main/java/com/ripple/BE/learning/persistence/jpa/repository/failquiz/FailQuizJpaRepository.java
  src/main/java/com/ripple/BE/learning/persistence/jpa/repository/learningset/UserLearningSetJpaRepository.java
  src/main/java/com/ripple/BE/learning/persistence/jpa/repository/quizscrap/QuizScrapJpaRepository.java
  src/main/java/com/ripple/BE/news/persistence/NewsScrapRepository.java
  src/main/java/com/ripple/BE/news/persistence/impl/NewsScrapRepositoryImpl.java
  src/main/java/com/ripple/BE/news/persistence/jpa/repository/newsscrap/NewsScrapJpaRepository.java
  src/main/java/com/ripple/BE/notification/persistence/NotificationRepository.java
  src/main/java/com/ripple/BE/notification/persistence/impl/NotificationRepositoryImpl.java
  src/main/java/com/ripple/BE/notification/persistence/jpa/repository/NotificationJpaRepository.java
  src/main/java/com/ripple/BE/post/application/PostCommandUseCase.java
  src/main/java/com/ripple/BE/post/application/impl/post/PostCommandService.java
  src/main/java/com/ripple/BE/post/persistence/CommentLikeRepository.java
  src/main/java/com/ripple/BE/post/persistence/CommentRepository.java
  src/main/java/com/ripple/BE/post/persistence/PostLikeRepository.java
  src/main/java/com/ripple/BE/post/persistence/PostRepository.java
  src/main/java/com/ripple/BE/post/persistence/PostScrapRepository.java
  src/main/java/com/ripple/BE/post/persistence/impl/post/CommentLikeRepositoryImpl.java
  src/main/java/com/ripple/BE/post/persistence/impl/post/CommentRepositoryImpl.java
  src/main/java/com/ripple/BE/post/persistence/impl/post/PostLikeRepositoryImpl.java
  src/main/java/com/ripple/BE/post/persistence/impl/post/PostRepositoryImpl.java
  src/main/java/com/ripple/BE/post/persistence/impl/post/PostScrapRepositoryImpl.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/comment/CommentJpaRepository.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/commentlike/CommentLikeJpaRepository.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/post/PostJpaRepository.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/postlike/PostLikeJpaRepository.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/postscrap/PostScrapJpaRepository.java
  src/main/java/com/ripple/BE/term/persistence/TermScrapRepository.java
  src/main/java/com/ripple/BE/term/persistence/impl/TermScrapRepositoryImpl.java
  src/main/java/com/ripple/BE/term/persistence/jpa/repository/termscrap/TermScrapJpaRepository.java
  src/main/java/com/ripple/BE/user/controller/UserController.java
  src/main/java/com/ripple/BE/user/exception/errorcode/UserErrorCode.java
  src/main/java/com/ripple/BE/user/repository/AttendanceLogRepository.java
  src/main/java/com/ripple/BE/user/repository/AttendanceRepository.java
  src/main/java/com/ripple/BE/user/repository/QuestRepository.java
  src/main/java/com/ripple/BE/user/repository/UserGoalRepository.java
  src/main/java/com/ripple/BE/user/repository/UserRepository.java
  src/main/java/com/ripple/BE/user/service/UserService.java
Labels: :sparkles: Feat

#118 [Feat] 게시글 조회 성능 개선을 위한 로컬/글로벌 캐시 도입 및 스크랩 여부 필드 제거
  build.gradle
  src/main/java/com/ripple/BE/global/config/RedisListenerConfig.java
  src/main/java/com/ripple/BE/global/config/cache/PostCacheKeyGenerator.java
  src/main/java/com/ripple/BE/global/config/cache/RedisConfig.java
  src/main/java/com/ripple/BE/learning/application/quiz/QuizRedisService.java
  src/main/java/com/ripple/BE/notification/application/sse/SseEmitterManager.java
  src/main/java/com/ripple/BE/post/application/PostQueryUseCase.java
  src/main/java/com/ripple/BE/post/application/ToktokQueryUseCase.java
  src/main/java/com/ripple/BE/post/application/cache/PostCache.java
  src/main/java/com/ripple/BE/post/application/cache/PostCacheKey.java
  src/main/java/com/ripple/BE/post/application/cache/PostCacheManager.java
  src/main/java/com/ripple/BE/post/application/cache/impl/CaffeineCache.java
  src/main/java/com/ripple/BE/post/application/cache/impl/RedisCache.java
  src/main/java/com/ripple/BE/post/application/cache/redis/PostCacheEvictionPublisher.java
  src/main/java/com/ripple/BE/post/application/cache/redis/PostCacheEvictionSubscriber.java
  src/main/java/com/ripple/BE/post/application/impl/post/PostCommandService.java
  src/main/java/com/ripple/BE/post/application/impl/post/PostQueryService.java
  src/main/java/com/ripple/BE/post/application/impl/toktok/ToktokAdminService.java
  src/main/java/com/ripple/BE/post/application/impl/toktok/ToktokQueryService.java
  src/main/java/com/ripple/BE/post/controller/PostController.java
  src/main/java/com/ripple/BE/post/controller/ToktokController.java
  src/main/java/com/ripple/BE/post/dto/response/PostPreviewResponseDTO.java
  src/main/java/com/ripple/BE/post/dto/response/ToktokPreviewResponseDTO.java
  src/main/java/com/ripple/BE/post/persistence/PostLikeRepository.java
  src/main/java/com/ripple/BE/post/persistence/PostRepository.java
  src/main/java/com/ripple/BE/post/persistence/PostScrapRepository.java
  src/main/java/com/ripple/BE/post/persistence/ToktokRepository.java
  src/main/java/com/ripple/BE/post/persistence/dto/PostWithImageDTO.java
  src/main/java/com/ripple/BE/post/persistence/dto/ToktokWithImageDTO.java
  src/main/java/com/ripple/BE/post/persistence/impl/post/PostLikeRepositoryImpl.java
  src/main/java/com/ripple/BE/post/persistence/impl/post/PostRepositoryImpl.java
  src/main/java/com/ripple/BE/post/persistence/impl/post/PostScrapRepositoryImpl.java
  src/main/java/com/ripple/BE/post/persistence/impl/toktok/ToktokRepositoryImpl.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/post/PostQueryRepository.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/post/PostQueryRepositoryImpl.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/post/ToktokQueryRepository.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/post/ToktokQueryRepositoryImpl.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/postlike/PostLikeQueryRepository.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/postlike/PostLikeQueryRepositoryImpl.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/postscrap/PostScrapQueryRepository.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/postscrap/PostScrapQueryRepositoryImpl.java
  src/main/java/com/ripple/BE/user/domain/User.java
  src/main/java/com/ripple/BE/user/service/MyPageService.java
  src/main/java/com/ripple/BE/user/service/UserService.java
Labels: :recycle: Refactor, :sparkles: Feat

#121 Feat : 이미지 용량 변경 (#120)
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: :sparkles: Feat

#124 [Refactor] 사용자 생성 시 학습 세트 자동 생성 이벤트 도입 (#119)
  src/main/java/com/ripple/BE/learning/application/learningset/LearningSetService.java
  src/main/java/com/ripple/BE/learning/application/learningset/event/UserCreatedEvent.java
  src/main/java/com/ripple/BE/user/service/UserService.java
Labels: :recycle: Refactor

#125 [Refactor] 경제톡톡 게시물, 게시물 QueryProjection 추가 및 기타 수정
  src/main/java/com/ripple/BE/post/application/impl/post/PostQueryService.java
  src/main/java/com/ripple/BE/post/application/impl/toktok/ToktokQueryService.java
  src/main/java/com/ripple/BE/post/dto/response/CommentResponseDTO.java
  src/main/java/com/ripple/BE/post/dto/response/PostResponseDTO.java
  src/main/java/com/ripple/BE/post/dto/response/ToktokResponseDTO.java
  src/main/java/com/ripple/BE/post/persistence/PostRepository.java
  src/main/java/com/ripple/BE/post/persistence/ToktokRepository.java
  src/main/java/com/ripple/BE/post/persistence/dto/CommentWithUserDTO.java
  src/main/java/com/ripple/BE/post/persistence/dto/PostDetailDTO.java
  src/main/java/com/ripple/BE/post/persistence/dto/ToktokDetailDTO.java
  src/main/java/com/ripple/BE/post/persistence/impl/post/PostRepositoryImpl.java
  src/main/java/com/ripple/BE/post/persistence/impl/toktok/ToktokRepositoryImpl.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/comment/CommentQueryRepositoryImpl.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/post/PostQueryRepository.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/post/PostQueryRepositoryImpl.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/post/ToktokQueryRepository.java
  src/main/java/com/ripple/BE/post/persistence/jpa/repository/post/ToktokQueryRepositoryImpl.java
Labels: :recycle: Refactor

#127 [Refactor] SSEEmitter 종료 로직 비동기 처리 및 간소화 (#117)
  src/main/java/com/ripple/BE/notification/application/sse/SseEmitterManager.java
Labels: :recycle: Refactor
