Repository IT-Cotato/10th-Economic-Learning-BE, pull requests merged in 2025-01, with the labels that each got.

#26 [Feat] Docker + EC2 + Github Action + Https Ci/Cd 배포 (#23)
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/java/com/ripple/BE/global/config/WebConfig.java
  src/main/java/com/ripple/BE/global/config/WebSecurityConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/keystore.p12
Labels: :earth_asia: Deploy

#30 Feat : 마이페이지 기능을 위한 저장기능을 구현한다
  src/main/java/com/ripple/BE/learning/controller/ConceptController.java
  src/main/java/com/ripple/BE/learning/controller/QuizController.java
  src/main/java/com/ripple/BE/learning/domain/concept/ConceptScrap.java
  src/main/java/com/ripple/BE/learning/repository/ConceptScrapRepository.java
  src/main/java/com/ripple/BE/learning/repository/QuizScrapRepository.java
  src/main/java/com/ripple/BE/learning/service/concept/ConceptService.java
  src/main/java/com/ripple/BE/learning/service/quiz/QuizService.java
Labels: :sparkles: Feat

#32 [Feat] 뉴스 기사 api 구현
  build.gradle
  src/main/java/com/ripple/BE/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/ripple/BE/learning/service/learningset/LearningAdminService.java
  src/main/java/com/ripple/BE/news/controller/NewsController.java
  src/main/java/com/ripple/BE/news/crawler/NewsCrawler.java
  src/main/java/com/ripple/BE/news/crawler/impl/FinanceNewsCrawler.java
  src/main/java/com/ripple/BE/news/crawler/impl/GlobalNewsCrawler.java
  src/main/java/com/ripple/BE/news/crawler/impl/IndustryNewsCrawler.java
  src/main/java/com/ripple/BE/news/crawler/impl/InvestmentNewsCrawler.java
  src/main/java/com/ripple/BE/news/crawler/impl/NormalNewsCrawler.java
  src/main/java/com/ripple/BE/news/crawler/impl/OtherNewsCrawler.java
  src/main/java/com/ripple/BE/news/crawler/impl/RealEstateNewsCrawler.java
  src/main/java/com/ripple/BE/news/domain/News.java
  src/main/java/com/ripple/BE/news/domain/NewsCategory.java
  src/main/java/com/ripple/BE/news/domain/NewsScrap.java
  src/main/java/com/ripple/BE/news/domain/NewsTerm.java
  src/main/java/com/ripple/BE/news/domain/type/NewsCategory.java
  src/main/java/com/ripple/BE/news/domain/type/NewsSort.java
  src/main/java/com/ripple/BE/news/dto/NewsDTO.java
  src/main/java/com/ripple/BE/news/dto/NewsListDTO.java
  src/main/java/com/ripple/BE/news/dto/response/NewsListResponse.java
  src/main/java/com/ripple/BE/news/dto/response/NewsResponse.java
  src/main/java/com/ripple/BE/news/exception/NewsException.java
  src/main/java/com/ripple/BE/news/exception/errorcode/NewsErrorCode.java
  src/main/java/com/ripple/BE/news/repository/news/NewsJdbcRepository.java
  src/main/java/com/ripple/BE/news/repository/news/NewsRepository.java
  src/main/java/com/ripple/BE/news/repository/news/NewsRepositoryCustom.java
  src/main/java/com/ripple/BE/news/repository/news/NewsRepositoryCustomImpl.java
  src/main/java/com/ripple/BE/news/repository/newscrap/NewsScrapRepository.java
  src/main/java/com/ripple/BE/news/service/NewsService.java
Labels: :sparkles: Feat

#34 [Feat] 용어 사전 api 구현
  src/main/java/com/ripple/BE/global/excel/ExcelUtils.java
  src/main/java/com/ripple/BE/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/ripple/BE/learning/service/learningset/LearningAdminService.java
  src/main/java/com/ripple/BE/term/controller/TermController.java
  src/main/java/com/ripple/BE/term/domain/Term.java
  src/main/java/com/ripple/BE/term/domain/TermCategory.java
  src/main/java/com/ripple/BE/term/domain/TermScrap.java
  src/main/java/com/ripple/BE/term/dto/TermDTO.java
  src/main/java/com/ripple/BE/term/dto/TermListDTO.java
  src/main/java/com/ripple/BE/term/dto/response/TermListResponse.java
  src/main/java/com/ripple/BE/term/dto/response/TermResponse.java
  src/main/java/com/ripple/BE/term/exception/TermException.java
  src/main/java/com/ripple/BE/term/exception/errorcode/TermErrorCode.java
  src/main/java/com/ripple/BE/term/repository/TermJdbcRepository.java
  src/main/java/com/ripple/BE/term/repository/TermRepository.java
  src/main/java/com/ripple/BE/term/repository/TermRepositoryCustom.java
  src/main/java/com/ripple/BE/term/repository/TermRepositoryCustomImpl.java
  src/main/java/com/ripple/BE/term/repository/TermScrapRepository.java
  src/main/java/com/ripple/BE/term/service/TermAdminService.java
  src/main/java/com/ripple/BE/term/service/TermService.java
  src/main/resources/static/excel/term.xlsx
Labels: :sparkles: Feat

#31 [Feat] 마이페이지 기능을 일부 구현한다 #25
  src/main/java/com/ripple/BE/learning/controller/ConceptController.java
  src/main/java/com/ripple/BE/learning/controller/QuizController.java
  src/main/java/com/ripple/BE/learning/dto/ConceptDTO.java
  src/main/java/com/ripple/BE/learning/dto/ConceptListDTO.java
  src/main/java/com/ripple/BE/learning/dto/FailQuizListDTO.java
  src/main/java/com/ripple/BE/learning/dto/QuizDTO.java
  src/main/java/com/ripple/BE/learning/dto/QuizListDTO.java
  src/main/java/com/ripple/BE/learning/dto/response/ConceptDetailResponse.java
  src/main/java/com/ripple/BE/learning/dto/response/FailQuizListResponse.java
  src/main/java/com/ripple/BE/learning/dto/response/FailQuizResponse.java
  src/main/java/com/ripple/BE/learning/dto/response/ScrapConceptListResponse.java
  src/main/java/com/ripple/BE/learning/dto/response/ScrapConceptResponse.java
  src/main/java/com/ripple/BE/learning/dto/response/ScrapQuizListResponse.java
  src/main/java/com/ripple/BE/learning/dto/response/ScrapQuizResponse.java
  src/main/java/com/ripple/BE/learning/exception/LearningException.java
  src/main/java/com/ripple/BE/learning/exception/QuizException.java
  src/main/java/com/ripple/BE/learning/exception/errorcode/LearningErrorCode.java
  src/main/java/com/ripple/BE/learning/exception/errorcode/QuizErrorCode.java
  src/main/java/com/ripple/BE/learning/repository/ConceptScrapRepository.java
  src/main/java/com/ripple/BE/learning/repository/QuizScrapRepository.java
  src/main/java/com/ripple/BE/learning/repository/concept/ConceptRepository.java
  src/main/java/com/ripple/BE/learning/repository/conceptScrap/ConceptScrapRepository.java
  src/main/java/com/ripple/BE/learning/repository/conceptScrap/ConceptScrapRepositoryCustom.java
  src/main/java/com/ripple/BE/learning/repository/conceptScrap/ConceptScrapRepositoryCustomImpl.java
  src/main/java/com/ripple/BE/learning/repository/learningSet/LearningSetRepository.java
  src/main/java/com/ripple/BE/learning/repository/learningSet/UserLearningSetRepository.java
  src/main/java/com/ripple/BE/learning/repository/quiz/QuizRepository.java
  src/main/java/com/ripple/BE/learning/repository/quiz/QuizRepositoryCustom.java
  src/main/java/com/ripple/BE/learning/repository/quiz/QuizRepositoryCustomImpl.java
  src/main/java/com/ripple/BE/learning/repository/quizScrap/QuizScrapRepository.java
  src/main/java/com/ripple/BE/learning/repository/quizScrap/QuizScrapRepositoryCustom.java
  src/main/java/com/ripple/BE/learning/repository/quizScrap/QuizScrapRepositoryCustomImpl.java
  src/main/java/com/ripple/BE/learning/service/LevelTestService.java
  src/main/java/com/ripple/BE/learning/service/concept/ConceptService.java
  src/main/java/com/ripple/BE/learning/service/learningset/LearningAdminService.java
  src/main/java/com/ripple/BE/learning/service/learningset/LearningSetService.java
  src/main/java/com/ripple/BE/learning/service/quiz/QuizService.java
  src/main/java/com/ripple/BE/post/dto/LikeCommentDTO.java
  src/main/java/com/ripple/BE/post/dto/LikeCommentListDTO.java
  src/main/java/com/ripple/BE/post/dto/response/LikeCommentListResponse.java
  src/main/java/com/ripple/BE/post/dto/response/LikeCommentResponse.java
  src/main/java/com/ripple/BE/post/repository/commentlike/CommentLikeRepository.java
  src/main/java/com/ripple/BE/post/repository/commentlike/CommentLikeRepositoryCustom.java
  src/main/java/com/ripple/BE/post/repository/commentlike/CommentLikeRepositoryCustomImpl.java
  src/main/java/com/ripple/BE/user/controller/UserController.java
  src/main/java/com/ripple/BE/user/service/MyPageService.java
  src/main/java/com/ripple/BE/user/service/UserProgressService.java
Labels: :sparkles: Feat

#39 [Feat] 카카오 로그인 방식 변경 (#12)
  src/main/java/com/ripple/BE/auth/client/KakaoApiClient.java
  src/main/java/com/ripple/BE/auth/controller/AuthControllerV2.java
  src/main/java/com/ripple/BE/auth/service/AuthService.java
  src/main/java/com/ripple/BE/global/config/WebSecurityConfig.java
  src/main/java/com/ripple/BE/user/domain/User.java
  src/main/java/com/ripple/BE/user/domain/type/BusinessType.java
  src/main/java/com/ripple/BE/user/domain/type/Job.java
  src/main/java/com/ripple/BE/user/dto/UpdateUserProfileRequest.java
  src/main/resources/application-local.yml
Labels: :recycle: Refactor, :sparkles: Feat

#40 [Feat] 알림 API 구현
  build.gradle
  src/main/java/com/ripple/BE/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/ripple/BE/notification/controller/NotificationController.java
  src/main/java/com/ripple/BE/notification/domain/Notification.java
  src/main/java/com/ripple/BE/notification/domain/NotificationType.java
  src/main/java/com/ripple/BE/notification/dto/NotificationDTO.java
  src/main/java/com/ripple/BE/notification/dto/NotificationListDTO.java
  src/main/java/com/ripple/BE/notification/dto/response/NotificationListResponse.java
  src/main/java/com/ripple/BE/notification/dto/response/NotificationResponse.java
  src/main/java/com/ripple/BE/notification/dto/response/UnreadCountResponse.java
  src/main/java/com/ripple/BE/notification/exception/NotificationException.java
  src/main/java/com/ripple/BE/notification/exception/errorcode/NotificationErrorCode.java
  src/main/java/com/ripple/BE/notification/repository/EmitterRepository.java
  src/main/java/com/ripple/BE/notification/repository/NotificationRepository.java
  src/main/java/com/ripple/BE/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/ripple/BE/notification/repository/NotificationRepositoryCustomImpl.java
  src/main/java/com/ripple/BE/notification/service/NotificationService.java
  src/main/java/com/ripple/BE/notification/service/SseEmitterManager.java
  src/main/java/com/ripple/BE/post/service/PostService.java
Labels: :sparkles: Feat

#38 [Feat] 챗봇 기능 구현
  build.gradle
  src/main/java/com/ripple/BE/chatbot/controller/ChatbotController.java
  src/main/java/com/ripple/BE/chatbot/domain/ChatMessage.java
  src/main/java/com/ripple/BE/chatbot/domain/ChatSession.java
  src/main/java/com/ripple/BE/chatbot/dto/ChatDTO.java
  src/main/java/com/ripple/BE/chatbot/dto/ChatListDTO.java
  src/main/java/com/ripple/BE/chatbot/dto/request/ChatRequest.java
  src/main/java/com/ripple/BE/chatbot/dto/response/ChatListResponse.java
  src/main/java/com/ripple/BE/chatbot/dto/response/ChatResponse.java
  src/main/java/com/ripple/BE/chatbot/repository/ChatbotRepository.java
  src/main/java/com/ripple/BE/chatbot/service/ChatbotService.java
  src/main/java/com/ripple/BE/user/domain/User.java
  src/main/resources/application.yml
Labels: :sparkles: Feat

#41 [Feat] 레벨테스트 리팩토링을 진행한다 (#14)
  src/main/java/com/ripple/BE/learning/controller/LevelTestController.java
  src/main/java/com/ripple/BE/learning/dto/QuizDTO.java
  src/main/java/com/ripple/BE/learning/dto/response/QuizResponse.java
  src/main/java/com/ripple/BE/learning/dto/response/RandomQuizResponse.java
  src/main/java/com/ripple/BE/learning/repository/quiz/QuizRepository.java
  src/main/java/com/ripple/BE/learning/service/LevelTestService.java
Labels: :recycle: Refactor

#44 퀴즈 진행 컨트롤러 전달 인자 수정 #42
  src/main/java/com/ripple/BE/learning/controller/QuizController.java
  src/main/java/com/ripple/BE/learning/dto/request/SubmitAnswerRequest.java
  src/main/java/com/ripple/BE/learning/service/quiz/QuizService.java
  src/main/java/com/ripple/BE/learning/validation/AnswerIndexValidator.java
  src/main/java/com/ripple/BE/learning/validation/ValidAnswerIndex.java
Labels: :recycle: Refactor
